name: Blogger Autopost Bokji

on:
  schedule:
    - cron: "0 18 * * *"   # 매일 UTC 18시 → 한국시간(UTC+9) 새벽 3시 실행
  workflow_dispatch:

jobs:
  autopost:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ blogger_token.pickle 복원
      - name: Restore blogger_token.pickle
        run: |
          echo "${{ secrets.BLOGGER_TOKEN_PKL_B64 }}" > blogger_token.pickle.b64
          certutil -decode blogger_token.pickle.b64 blogger_token.pickle

      # ✅ cc.json 복원
      - name: Restore cc.json
        run: |
          echo "${{ secrets.CC_JSON_B64 }}" > cc.json.b64
          certutil -decode cc.json.b64 cc.json

      # ✅ sheetapi.json 복원
      - name: Restore sheetapi.json
        run: |
          echo "${{ secrets.SHEETAPI_JSON }}" > sheetapi.json.b64
          certutil -decode sheetapi.json.b64 sheetapi.json

      # ✅ openai.json 복원
      - name: Restore openai.json
        run: |
          echo "${{ secrets.OPENAI_JSON_B64 }}" > openai.json.b64
          certutil -decode openai.json.b64 openai.json

      # ✅ 2nd.json (Google Drive 키) 복원
      - name: Restore 2nd.json
        run: |
          echo "${{ secrets.DRIVE_JSON_B64 }}" > 2nd.json.b64
          certutil -decode 2nd.json.b64 2nd.json

      - name: Run autopost
        run: python blogger_bokj.py
